export const ROUTES = {
  LOGIN: '/login',
  LANDING: '/landing',
  SIGNUP: '/login/signup',
  MEMORY_LIST: '/memory',
  MEMORY_DETAIL: (memoryId: string | number) => `/memory/${memoryId}`,
  MEMORY_REGISTER: '/memory/register',
  POST_DETAIL: (memoryId: string | number, postId: string | number) => `/memory/${memoryId}/post/${postId}`,
  POST_REGISTER: (memoryId: string | number) => `/memory/${memoryId}/post/register`,
  MAP: '/map',
  CALENDAR: '/calendar',
  GUEST_BOOK: (id: string | number) => `/guest-book/${id}`,
  NOTIFICATION_LIST: '/notification',
  EDIT_PROFILE: '/edit-profile',
  ADD_PROFILE_IMAGE: '/add-profile-image',
  MEMBER_LIST: '/member-list',
  TEST: '/test',
}
