export const ROUTES = {
  LOGIN: '/login',
  LANDING: '/landing',
  SIGNUP: '/login/signup',
  HOME: '/home',
  MEMORY_LIST: '/home/memory',
  MEMORY_DETAIL: (memoryId: string | number) => `/memory/${memoryId}`,
  MEMORY_REGISTER: '/memory/register',
  MEMORY_EDIT: (memoryId: string | number) => `/memory/${memoryId}/edit`,
  POST_DETAIL: (memoryId: string | number, postId: string | number) => `/memory/${memoryId}/post/${postId}`,
  POST_REGISTER: (memoryId: string | number) => `/memory/${memoryId}/post/register`,
  POST_EDIT: (memoryId: string | number, postId: string | number) => `/memory/${memoryId}/post/${postId}/edit`,
  MAP: '/home/map',
  CALENDAR: '/home/calendar',
  GUEST_BOOK: (associateId?: string | number) => `/home/guest-book/${associateId || 'me'}`,
  NOTIFICATION_LIST: '/notification',
  EDIT_PROFILE: '/edit-profile',
  ADD_PROFILE_IMAGE: (associateId: string | number) => `/add-profile-image/${associateId}`,
  MEMBER_LIST: '/member-list',
  TEST: '/test',
}
