import {
  Camera,
  Cat,
  ConfoundedCircle,
  CrownStar,
  CupStar,
  Danger,
  Eye,
  EyeScan,
  FaceScanCircle,
  Gift,
  HandShake,
  HandStars,
  Health,
  Hearts,
  History2,
  Home2,
  Leaf,
  Logout2,
  Masks,
  Muted,
  PeopleNearby,
  Printer,
  QuestionCircle,
  Running,
  StarAngle,
  StarShine,
  StarsLine,
  Text,
  ThreeSquares,
  UserHandUp,
  UserRounded,
  Waterdrops,
  Wind,
} from '@solar-icons/react'
import type { Icon } from '@solar-icons/react/lib/types'

interface IBadge {
  name: string
  color: string
  backgroundColor: string
  border: string
  icon: Icon
}

export const BADGES: Record<number, IBadge> = {
  1: {
    name: '시간빌게이츠',
    color: '#193676',
    backgroundColor: '#BBE4FF',
    border: '#547ACA',
    icon: History2,
  },
  2: {
    name: '관상가',
    color: '#FFF632',
    backgroundColor: '#333C64',
    border: '#333C64',
    icon: Eye,
  },
  3: {
    name: '다중인격',
    color: '#F9F0FF',
    backgroundColor: '#B37FEB',
    border: '#B37FEB',
    icon: Masks,
  },
  4: {
    name: 'FFFFFF',
    color: '#E2CFEB',
    backgroundColor: '#313131',
    border: '#A40BDB',
    icon: ConfoundedCircle,
  },
  5: {
    name: 'T발 C야?',
    color: '#F7B998',
    backgroundColor: '#2A0810',
    border: '#2A0810',
    icon: Text,
  },
  6: {
    name: '리액션공장',
    color: '#FF8181',
    backgroundColor: '#292524',
    border: '#292524',
    icon: FaceScanCircle,
  },
  7: {
    name: '입에서주스가주르륵',
    color: '#FF9E17',
    backgroundColor: '#F8F8F8',
    border: '#FF9E17',
    icon: Waterdrops,
  },
  8: {
    name: '변검술사',
    color: '#ED82D8',
    backgroundColor: '#413341',
    border: '#ED82D8',
    icon: ThreeSquares,
  },
  9: {
    name: '파파라치',
    color: '#F0EFB9',
    backgroundColor: '#330A6D',
    border: '#5D7BBE',
    icon: Camera,
  },
  10: {
    name: '전문찍새',
    color: '#74D4FF',
    backgroundColor: '#000',
    border: '#000',
    icon: EyeScan,
  },
  11: {
    name: '마니또',
    color: '#FBECBB',
    backgroundColor: '#C933BB',
    border: '#94546F',
    icon: Gift,
  },
  12: {
    name: '민들레? 노브랜드?',
    color: '#FF9511',
    backgroundColor: '#FFFF69',
    border: '#F57043',
    icon: QuestionCircle,
  },
  13: {
    name: 'GMG',
    color: '#515F62',
    backgroundColor: '#A1EDF2',
    border: '#515F62',
    icon: Running,
  },
  14: {
    name: '업적헌터#kill',
    color: '#0C0A09',
    backgroundColor: '#FF4758',
    border: '#0C0A09',
    icon: CupStar,
  },
  15: {
    name: '홈 스윗 홈',
    color: '#E7F6AF',
    backgroundColor: '#008C32',
    border: '#00C84F',
    icon: Home2,
  },
  16: {
    name: '13일의 금요일',
    color: '#000000',
    backgroundColor: '#FFFFFF',
    border: '#000000',
    icon: Danger,
  },
  17: {
    name: '씽씽씽',
    color: '#D6E4FF',
    backgroundColor: '#0033AA',
    border: '#0033AA',
    icon: Wind,
  },
  18: {
    name: '팅팅팅',
    color: '#F9F0F0',
    backgroundColor: '#F23333',
    border: '#A37171',
    icon: StarsLine,
  },
  19: {
    name: '쿠로네코',
    color: '#FFF',
    backgroundColor: '#000',
    border: '#000',
    icon: Cat,
  },
  20: {
    name: '횬딘곤듀',
    color: '#FFE8EF',
    backgroundColor: '#FF7AA1',
    border: '#94C3FD',
    icon: Health,
  },
  21: {
    name: '귀한곳에누추한분이',
    color: '#3666A2',
    backgroundColor: '#E6F7FF',
    border: '#0050B3',
    icon: Logout2,
  },
  22: {
    name: '뤼전드',
    color: '#FFCC00',
    backgroundColor: '#000',
    border: '#000',
    icon: CrownStar,
  },
  23: {
    name: '주피티',
    color: '#95E2C0',
    backgroundColor: '#09112B',
    border: '#0058C4',
    icon: Printer,
  },
  24: {
    name: '신',
    color: '#F5E984',
    backgroundColor: '#433633',
    border: '#F4A73E ',
    icon: HandStars,
  },
  25: {
    name: '그녀석',
    color: '#D1D1D1',
    backgroundColor: '#818181',
    border: '#BEBEBE',
    icon: UserRounded,
  },
  26: {
    name: '인형',
    color: '#EB2F96',
    backgroundColor: '#FFF0F6',
    border: '#EB2F96',
    icon: PeopleNearby,
  },
  27: {
    name: '닥치',
    color: '#FF4230',
    backgroundColor: '#282828',
    border: '#E9210E',
    icon: Muted,
  },
  28: {
    name: 'ㅁㅇㅁㅇ',
    color: '#FFF4F7',
    backgroundColor: '#FF5F60',
    border: '#AE3A3E',
    icon: UserHandUp,
  },
  29: {
    name: '내절친',
    color: '#E3E08B',
    backgroundColor: '#41415D',
    border: '#3A885F',
    icon: StarAngle,
  },
  30: {
    name: 'GAY',
    color: '#F9F1F3',
    backgroundColor: '#C32C5C',
    border: '#F5A34D',
    icon: Hearts,
  },
  31: {
    name: '드디어봐주는구나',
    color: '#FFFFFF',
    backgroundColor: '#498FD6',
    border: '#FBC13C',
    icon: HandShake,
  },
  32: {
    name: '현지',
    color: '#5C4231',
    backgroundColor: '#FDFDFD',
    border: '#D99EA2',
    icon: StarShine,
  },
  33: {
    name: '랑이와싹이',
    color: '#697F38',
    backgroundColor: '#FFFF91',
    border: '#96DB59',
    icon: Leaf,
  },
}
